feat: Add validation step for input values.

diff --git a/.github/workflows/test-localtunnel.yml b/.github/workflows/test-localtunnel.yml
--- a/.github/workflows/test-localtunnel.yml
+++ b/.github/workflows/test-localtunnel.yml
@@ -16,7 +16,7 @@ on:
       environment:
         description: 'Select an environment'
         required: true
-        default: 'validation'
+        default: 'Validation'
         type: choice
         options:
           - Validation
@@ -27,6 +27,28 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Validate inputs
+      run: |
+        environment="${{ github.event.inputs.environment }}"
+        tag="${{ github.event.inputs.tag }}"
+    
+        # Define a regex pattern that allows only letters, numbers, underscores, and hyphens
+        pattern='^[a-zA-Z0-9_-]+$'
+    
+        # Check 'environment' input
+        if [[ ! "$environment" =~ $pattern ]]; then
+          echo "Error: 'environment' contains invalid characters. Only letters, numbers, underscores, and hyphens are allowed."
+          exit 1
+        fi
+    
+        # Check 'tag' input
+        if [[ ! "$tag" =~ $pattern ]]; then
+          echo "Error: 'tag' contains invalid characters. Only letters, numbers, underscores, and hyphens are allowed."
+          exit 1
+        fi
+    
+        echo "Inputs are valid."
+
     - name: Checkout code
       uses: actions/checkout@v4.1.7
       with:
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,6 +16,29 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        environment="${{ inputs.environment }}"
+        tag="${{ inputs.tag }}"
+
+        # Define a regex pattern that allows only letters, numbers, underscores, and hyphens
+        pattern='^[a-zA-Z0-9_-]+$'
+
+        # Check 'environment' input
+        if [[ ! "$environment" =~ $pattern ]]; then
+          echo "Error: 'environment' contains invalid characters. Only letters, numbers, underscores, and hyphens are allowed."
+          exit 1
+        fi
+
+        # Check 'tag' input
+        if [[ ! "$tag" =~ $pattern ]]; then
+          echo "Error: 'tag' contains invalid characters. Only letters, numbers, underscores, and hyphens are allowed."
+          exit 1
+        fi
+
+        echo "Inputs are valid."
+
     - name: Checkout code
       uses: actions/checkout@v4.1.7
       with:
